### ISSUE TITLE
[dattri.func.projection.py] self.proj_type has incompatible naming with fast_jl function

### ISSUE THREAD

**Issue by KurisuTheAmadeus** [TRAIS-Lab/dattri#119]
## Bug description

on line 374 of projection.py
```python
        function_name = f"project_{self.proj_type}_{effective_batch_size}"
``` 
the current setup will result in something like
```python
       function_name = 'project_ProjectionType.rademacher_32'
```
but it should be 
```python
     function_name = 'project_rademacher_32'
```
Otherwise the execution will fail on next line
```python
        fn = getattr(fast_jl, function_name)
```

**Comment by tingwl0122** [comment]
Hi @KurisuTheAmadeus @TheaperDeng 
I don't think we have any problem calling TRAK right now?

If you print `self.proj_type`, it will indeed give you `ProjectionType.rademacher`;
but `function_name` will still be `project_rademacher_32` anyway

**Comment by KurisuTheAmadeus** [comment]
Yeah I believe this issue has been resolved by one of the recent updates. Now I use it without facing any problem. I will close this issue for now
