### ISSUE TITLE
Minor issue with precompute_data_ratio in Arnoldi implementation

### ISSUE THREAD

**Issue by charles-pyj** [TRAIS-Lab/dattri#136]
In line 412 of `influence_function.py`:
` # Assuming that full_train_dataloader has only one batch`
`iter_number = math.ceil(len(full_train_dataloader) * self.precompute_data_ratio)`
If `full_train_loader` has one batch the length returns one and thus no matter what ratio is provided full data will be precomputed. Not sure if this is intended.

**Comment by jiaqima** [comment]
Thanks for catching it. That is an outdated comment that should be removed

**Comment by charles-pyj** [comment]
Got it! If there are multiple batches it makes sense.
